### ISSUE TITLE
FMPy Gui intialization

### ISSUE THREAD

**Issue by M1997el** [CATIA-Systems/FMPy#573]
Hello, 

I am trying to intialize the FMPy Gui on my Computer. I constantly getting the following error:
![grafik](https://github.com/CATIA-Systems/FMPy/assets/121871460/9a2990fb-69a2-4848-a28a-53dd708b944e)
 
The problem could't be solved, even after uninstalling and reinstalling the PYQt5 Package. Is anybody familiar with this problem? I would be very thankfull for a quick response.

Kind Regards

**Comment by K-Beeser** [comment]
Hi all, 

I also get an **import error** when opening the gui via `python -m fmpy.gui`: `ImportError: cannot import name 'QtWebEngineWidgets'`. 

I am using _Python 3.10.11_ on a _Windows_ computer and `pip list` reveals the following versions of _pyqt5_ and _pyqtgraph_: 

- PyQt5              5.15.9
- PyQt5-Qt5          5.15.2
- PyQt5-sip          12.12.1
- pyqtgraph          0.13.3

The error occurs with _fmpy 0.3.14_ and _0.3.15_. Everything works fine with _0.3.13_. 

Best Regards!

**Comment by t-sommer** [comment]
Can you share steps to reproduce the problem with a fresh conda environment?

**Comment by t-sommer** [comment]
Can you share steps to reproduce the problem with a fresh conda environment?

**Comment by K-Beeser** [comment]
**solved** the _ImportError: cannot import name 'QtWebEngineWidgets'_ by manually adding _PyQtWebEngine_ to the conda environment: 

**Manual installation** (steps derived from _fmpy.readthedocs.io_):
```
conda create -n fmpy_env python=3.10
conda activate fmpy_env
pip install fmpy
pip install pyqt5
pip install pyqtgraph
python -m fmpy.gui
```
>>> ImportError: cannot import name 'QtWebEngineWidgets'
>>>

**Adding PyQtWebEngine**:

```
pip install PyQtWebEngine
python -m fmpy.gui
```
>>> Working as expected
>>>

**Complete installation** (alternatively): 

```
conda create -n fmpy_env python=3.10
conda activate fmpy_env
pip install fmpy[complete]
python -m fmpy.gui
```

>>> Working as expected
>>>

**Comment by t-sommer** [comment]
This problem should not occur if you follow the [installation instructions](https://github.com/CATIA-Systems/FMPy#installation).
